CREATE DATABASE IF NOT EXISTS CRUD_WEB;

USE CRUD_WEB;

CREATE TABLE usuarios (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	cpf VARCHAR(15) NOT NULL,
	nascimento DATE,
	peso INT(10),
	estado VARCHAR(40),
	UNIQUE (cpf)
) ENGINE MyISAM;

